//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cimsco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.SummaryDatas = new HashSet<SummaryData>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SummaryData> SummaryDatas { get; set; }
    }
}
