//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cimsco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryData
    {
        public int SummaryDataId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public Nullable<decimal> Value3 { get; set; }
        public Nullable<decimal> Value4 { get; set; }
        public Nullable<decimal> Value5 { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
