#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Cimsco.EntityDataModel;

namespace Cimsco.EntityDataModel	
{
	public partial class AspNetUser
	{
		private string _id;
		public virtual string Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private bool _emailConfirmed;
		public virtual bool EmailConfirmed
		{
			get
			{
				return this._emailConfirmed;
			}
			set
			{
				this._emailConfirmed = value;
			}
		}
		
		private string _passwordHash;
		public virtual string PasswordHash
		{
			get
			{
				return this._passwordHash;
			}
			set
			{
				this._passwordHash = value;
			}
		}
		
		private string _securityStamp;
		public virtual string SecurityStamp
		{
			get
			{
				return this._securityStamp;
			}
			set
			{
				this._securityStamp = value;
			}
		}
		
		private string _phoneNumber;
		public virtual string PhoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				this._phoneNumber = value;
			}
		}
		
		private bool _phoneNumberConfirmed;
		public virtual bool PhoneNumberConfirmed
		{
			get
			{
				return this._phoneNumberConfirmed;
			}
			set
			{
				this._phoneNumberConfirmed = value;
			}
		}
		
		private bool _twoFactorEnabled;
		public virtual bool TwoFactorEnabled
		{
			get
			{
				return this._twoFactorEnabled;
			}
			set
			{
				this._twoFactorEnabled = value;
			}
		}
		
		private DateTime? _lockoutEndDateUtc;
		public virtual DateTime? LockoutEndDateUtc
		{
			get
			{
				return this._lockoutEndDateUtc;
			}
			set
			{
				this._lockoutEndDateUtc = value;
			}
		}
		
		private bool _lockoutEnabled;
		public virtual bool LockoutEnabled
		{
			get
			{
				return this._lockoutEnabled;
			}
			set
			{
				this._lockoutEnabled = value;
			}
		}
		
		private int _accessFailedCount;
		public virtual int AccessFailedCount
		{
			get
			{
				return this._accessFailedCount;
			}
			set
			{
				this._accessFailedCount = value;
			}
		}
		
		private string _userName;
		public virtual string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		
		private IList<AspNetUserLogin> _aspNetUserLogins = new List<AspNetUserLogin>();
		public virtual IList<AspNetUserLogin> AspNetUserLogins
		{
			get
			{
				return this._aspNetUserLogins;
			}
		}
		
		private IList<AspNetUserClaim> _aspNetUserClaims = new List<AspNetUserClaim>();
		public virtual IList<AspNetUserClaim> AspNetUserClaims
		{
			get
			{
				return this._aspNetUserClaims;
			}
		}
		
		private IList<AspNetRole> _aspNetRoles = new List<AspNetRole>();
		public virtual IList<AspNetRole> AspNetRoles
		{
			get
			{
				return this._aspNetRoles;
			}
		}
		
	}
}
#pragma warning restore 1591
