#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Cimsco.EntityDataModel;

namespace Cimsco.EntityDataModel	
{
	public partial class CimscoModel : OpenAccessContext, ICimscoModelUnitOfWork
	{
		private static string connectionStringName = @"Connection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EntitiesModel.rlinq");
		
		public CimscoModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public CimscoModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public CimscoModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public CimscoModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public CimscoModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<SummaryDatum> SummaryData 
		{
			get
			{
				return this.GetAll<SummaryDatum>();
			}
		}
		
		public IQueryable<AspNetUser> AspNetUsers 
		{
			get
			{
				return this.GetAll<AspNetUser>();
			}
		}
		
		public IQueryable<AspNetUserLogin> AspNetUserLogins 
		{
			get
			{
				return this.GetAll<AspNetUserLogin>();
			}
		}
		
		public IQueryable<AspNetUserClaim> AspNetUserClaims 
		{
			get
			{
				return this.GetAll<AspNetUserClaim>();
			}
		}
		
		public IQueryable<AspNetRole> AspNetRoles 
		{
			get
			{
				return this.GetAll<AspNetRole>();
			}
		}
		
		public IQueryable<__MigrationHistory> __MigrationHistories 
		{
			get
			{
				return this.GetAll<__MigrationHistory>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of CimscoModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of CimscoModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface ICimscoModelUnitOfWork : IUnitOfWork
	{
		IQueryable<SummaryDatum> SummaryData
		{
			get;
		}
		IQueryable<AspNetUser> AspNetUsers
		{
			get;
		}
		IQueryable<AspNetUserLogin> AspNetUserLogins
		{
			get;
		}
		IQueryable<AspNetUserClaim> AspNetUserClaims
		{
			get;
		}
		IQueryable<AspNetRole> AspNetRoles
		{
			get;
		}
		IQueryable<__MigrationHistory> __MigrationHistories
		{
			get;
		}
	}
}
#pragma warning restore 1591
