#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Cimsco.EntityDataModel	
{
	public partial class SummaryDatum
	{
		private int _summaryDataId;
		public virtual int SummaryDataId
		{
			get
			{
				return this._summaryDataId;
			}
			set
			{
				this._summaryDataId = value;
			}
		}
		
		private DateTime? _date;
		public virtual DateTime? Date
		{
			get
			{
				return this._date;
			}
			set
			{
				this._date = value;
			}
		}
		
		private decimal? _value1;
		public virtual decimal? Value1
		{
			get
			{
				return this._value1;
			}
			set
			{
				this._value1 = value;
			}
		}
		
		private decimal? _value2;
		public virtual decimal? Value2
		{
			get
			{
				return this._value2;
			}
			set
			{
				this._value2 = value;
			}
		}
		
		private decimal? _value3;
		public virtual decimal? Value3
		{
			get
			{
				return this._value3;
			}
			set
			{
				this._value3 = value;
			}
		}
		
		private decimal? _value4;
		public virtual decimal? Value4
		{
			get
			{
				return this._value4;
			}
			set
			{
				this._value4 = value;
			}
		}
		
		private decimal? _value5;
		public virtual decimal? Value5
		{
			get
			{
				return this._value5;
			}
			set
			{
				this._value5 = value;
			}
		}
		
		private string _customerId;
		public virtual string CustomerId
		{
			get
			{
				return this._customerId;
			}
			set
			{
				this._customerId = value;
			}
		}
		
	}
}
#pragma warning restore 1591
